---
driver:
  name: docker

platforms:
  - name: centos-6.8
    driver_config:
      privileged: true
      use_sudo: false
      provision_command:
        - yum install -y initscripts net-tools wget && curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 12.6.0 && rm install.sh

  - name: centos-7.2
    driver_config:
      privileged: true
      use_sudo: false
      provision_command:
        - yum install -y initscripts net-tools wget && curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 12.6.0 && rm install.sh

provisioner:
  name: chef_solo
  require_chef_omnibus: "12.6.0"
  client_rb:
    add_formatter: min
  solo_rb:
    file_atomic_update: false

suites:
  - name: default
    run_list:
      - recipe[wkhtmltopdf::default]
    attributes:
